// Auto-generated by scripts/build-project-thumbnails.js. Do not edit.
export const generatedProjectThumbnails: Record<string, string> = {
  "index_animation": "/static/images/generated/project-thumbs/index_animation.webp"
};
