// Auto-generated by scripts/build-project-thumbnails.js. Do not edit.
export const generatedProjectThumbnails: Record<string, string> = {
  "demo": "/static/images/generated/project-thumbs/demo.webp",
  "demo2": "/static/images/generated/project-thumbs/demo2.webp",
  "animation": "/static/images/generated/project-thumbs/animation.webp"
};
